### ISSUE TITLE
A little more documentation please (e.g. Readme, Repository description).

### ISSUE THREAD

**Issue by shea-parkes** [milliman/ADA_IntroToR_Shiny#1]
Hey @MKullowatz , could you please add a bit more documentation to this repository:
  - [x] Add a description to the repository (at the top of the page)
  - [x] Author a root `readme.md`
    - [x] At least briefly state the purpose
    - [x] Be sure to add the "for educational purposes only" disclaimer
    - [x] Add some notes about setting up the environment (e.g. R version, package versions)

Thanks!

**Comment by MKullowatz** [comment]
https://www.quora.com/How-do-you-say-I-would-do-anything-for-you-in-a-casual-way

**Comment by shea-parkes** [comment]
Looks good to me.  Thanks sir.

Outta curiosity, what does the leading "ADA" mean?

**Comment by MKullowatz** [comment]
It's a local developers' academy here in Seattle: https://www.adadevelopersacademy.org/. We're presenting this intro for some of their students today.
